version: '3.9'
services:
  postgres:
    container_name: library-forge-dev
    image: postgres:16.2
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
