version: "3"

services:
  postgres:
    container_name: dev-library-db
    image: postgres:16.2
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
