name: Java GitHub CI

run-name: Running default CI-checks for code pushed by ${{ github.actor }}

permissions: write-all

on:
  push:

jobs:
  build:
    name: Build application
    uses: ./.github/workflows/run_build_job.yml

  test:
    needs: build
    name: Test application
    uses: ./.github/workflows/run_tests_job.yml

  sonarlint:
    needs: build
    name: Check application style via sonarlint
    uses: ./.github/workflows/run_sonarlint_job.yml

  checkstyle:
    needs: build
    name: Check application style via checkstyle
    uses: ./.github/workflows/run_checkstyle_job.yml

  publish:
    name: Publish package to the Repsy Maven Repository
    needs: [test, sonarlint, checkstyle]
    secrets: inherit
    uses: ./.github/workflows/run_lib_publish_job.yml
