name: Test

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup build
        env:
          MAVEN_USERNAME: ${{ secrets.REPSY_LOGIN }}
          MAVEN_PASSWORD: ${{ secrets.REPSY_PASS }}
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle test
        run: ./gradlew test
