name: Publish ciphers library to a Repsy Maven Repository

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java for publishing to the Repsy Maven Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.REPSY_LOGIN }}
          MAVEN_PASSWORD: ${{ secrets.REPSY_PASS }}
          MAVEN_URL: ${{ secrets.REPSY_URL }}
        run: |
          echo "Received MAVEN_USERNAME: $MAVEN_USERNAME"
          echo "Received MAVEN_PASSWORD: $MAVEN_PASSWORD"
          echo "Received MAVEN_URL: $MAVEN_URL"
          ./gradlew publish
